@startuml Registrar usuario

hide empty description

state RegistrarUsuario{
    [*] --> EsperandoDatos
    EsperandoDatos --> ValidandoDatos : Usuario ingresa datos
    ValidandoDatos --> UsuarioRegistrado : Datos válidos
    ValidandoDatos --> ErrorValidacion : Datos inválidos
    ErrorValidacion --> EsperandoDatos : Reintentar
    UsuarioRegistrado --> [*] : Registro exitoso
}

@enduml
