@startuml Iniciar sesión uc2

hide empty description

state iniciarSesion{
    [*] --> EsperandoLogin
    EsperandoLogin --> ValidandoCredenciales : Usuario ingresa credenciales
    ValidandoCredenciales --> SesionActiva : Credenciales correctas
    ValidandoCredenciales --> ErrorCredenciales : Credenciales incorrectas
    ErrorCredenciales --> EsperandoLogin : Reintentar
    SesionActiva --> [*] : Inicio de sesión exitoso
}

@enduml
