@startuml Moderador
state Moderador {
    [*] --> Inactivo
    
    Inactivo --> Activo : Iniciar sesión
    Activo --> Inactivo : Cerrar sesión
    
    Activo --> RevisandoPublicacion : Revisar publicación
    RevisandoPublicacion --> EliminandoPublicacion : Decidir eliminar
    RevisandoPublicacion --> AprobandoPublicacion : Aprobar publicación
    EliminandoPublicacion --> Activo : Eliminar publicación
    AprobandoPublicacion --> Activo : Aprobar publicación 

    Activo --> RevisandoEvento : Revisar evento
    RevisandoEvento --> EliminandoEvento : Decidir eliminar
    RevisandoEvento --> AprobandoEvento : Aprobar evento
    EliminandoEvento --> Activo : Eliminar evento
    AprobandoEvento --> Activo : evento Aprobar

    Activo --> RevisandoComentario : Revisar comentario
    RevisandoComentario --> EliminandoComentario : Decidir eliminar
    RevisandoComentario --> AprobandoComentario : Aprobar comentario
    EliminandoComentario --> Activo :  Eliminar comentario
    AprobandoComentario --> Activo : Aprobar comentario
}

@enduml