@startuml UC2 Iniciar sesión

left to right direction

Actor ":Usuario" as u

entity ":Usuario" as sesion

control ":GestorDeInicioDeSesión" as gestor

boundary ":FormularioDeInicioDeSesión" as reg

boundary ":Dashboard" as dash

u -- reg
reg -- gestor
gestor -- sesion
gestor -- dash

@enduml