@startuml UC13 Revisar Calendario
left to right direction

Actor " :Usuario" as user

boundary " :VistaCalendario" as IC

control " :GestorDeCalendario" as CC

entity " :Calendario" as C
entity " :Evento" as E 
control ":GestorDeEventos" as GE
user -- IC
IC -- CC
CC -- C 

GE - E 
C - GE

@enduml