@startuml UC2 Iniciar sesión

left to right direction

Actor ":Usuario" as u

entity ":Sesión de usuario" as sesion
control ":Gestor de inicio de sesión" as gestor
boundary ":Formulario de inicio de sesión" as reg

u ---- reg : -->\n//1: IngresarDatosUsuario()//
reg ---- gestor : -->\n//2: enviarDatosUsuario()// \n  <--\n//5: InicioExitoso()// 
gestor ---- sesion : -->\n //3: VerificarDatos()// \n <--\n//4: InicioExitoso()// 

@enduml