@startuml UC7 Hacer una publicación

left to right direction

Actor ":Profesor" as profe
Actor ":Personal de apoyo" as pa
Actor ":Moderador" as moderador

boundary ":Formulario de datos de la publicación" as form
control ":Gestor de publicaciones" as gestor
control ":Gestor de aprobación de publicación" as gestorP
entity ":Publicación" as p
entity ":Calendario" as c
entity ":Moderador" as mod
boundary ":Solicitud de publicación" as soli

profe -- form
pa -- form
moderador -- form
form -- gestor
gestor -- p
gestor -- c
gestor -- soli
soli -- gestorP
gestorP -- mod

@enduml