@startuml UC7 Hacer una publicación

left to right direction

Actor ":Moderador" as moderador
Actor ":Profesor" as profe
Actor ":Personal de apoyo" as pa

boundary ":FormularioDePublicación" as form
control ":GestorDePublicaciones" as gestor
entity ":Publicación" as p

profe -- form
pa -- form
moderador -- form
form -- gestor
gestor -- p

@enduml