@startuml UC17 Revisar Evento o Publicación

left to right direction

Actor ":Moderador" as moderador

boundary ":VistaDeRevisión" as form
control ":GestorDeRevisión" as gestor
entity ":Publicación" as p
entity ":Evento" as e
boundary ":VistaDeEvento" as VistE
boundary ":VistaDePublicación" as VistaP

moderador -- form : -->\n//1: RevisarEventos-Publicaciones()//
form -- gestor : -->\n//2: SolicitarDatos()//
gestor -- p: -->\n//3: SolicitarPublicación()// \n <--\n//4: EnviarPublicación()// \n -->\n//9: GuardarEstado()//
gestor -- e: -->\n//3: SolicitarEvento()// \n <--\n//4: EnviarEvento()// \n -->\n//9: GuardarEstado()//
VistE -- gestor: <--\n//5: CambiarVistaEvento()// \n -->\n//8: CambiarEstado()//
VistaP --gestor: <--\n//5: CambiarVistaPublicación()// \n -->\n//8: CambiarEstado()//
moderador -- VistE : <--\n//6: MostrarVistaEvento()// \n -->\n//7: AprobarRechazar()//
moderador -- VistaP : <--\n//6: MostrarVistaPublicación()// \n -->\n//7: AprobarRechazar()//

@enduml