@startuml UC18 Aprobar Evento o Publicación

left to right direction

'Analisis

Actor ":Moderador" as moderador

control ":GestorDeRevisión" as gestor
entity ":Publicación" as p
entity ":Evento" as e
boundary ":VistaDeEvento" as VistE
boundary ":VistaDePublicación" as VistaP

'Relaciones analisis
gestor -- p
gestor -- e
VistE -- gestor
VistaP -- gestor
moderador -- VistE 
moderador -- VistaP 

'Diseño

Actor ":Moderador" as moderador2

agent "GestorDeRevision" as gestorRevision
agent "Publicacion" as publicacion
agent "Evento" as evento
agent "VistaDeEvento" as VistaDeEvento
agent "VistaDePublicación" as VistaDePublicación

'Relaciones diseño

moderador2 -- VistaDeEvento
moderador2 -- VistaDePublicación
VistaDeEvento -- gestorRevision
VistaDePublicación -- gestorRevision
gestorRevision -- evento
gestorRevision -- publicacion

'trazas
VistaDeEvento <.... VistE : traza
VistaDePublicación <.... VistaP : traza
gestorRevision <.... gestor : traza
evento <.... e : traza
publicacion <.... p : traza

@enduml