@startuml UC13 Revisar Calendario Traza

left to right direction

' Análisis

Actor ":Usuario" as u_an

boundary ":VistaCalendario" as IC
control ":GestorDeCalendario" as CC
entity ":Calendario" as C
control ":GestorDeEventos" as GE
entity ":Evento" as E

u_an -- IC
IC -- CC
CC -- C
C -- GE
GE -- E

'Diseño

Actor ":Usuario" as user

agent "VistaCalendario" as DVC
agent "GestorDeCalendario" as DGC
agent "Calendario" as dcal
agent "GestorDeEventos" as DGE
agent "Evento" as devent

' Relaciones diseño

user -- DVC
IC ..> DVC : traza
CC ..> DGC : traza
C ..> dcal : traza
GE ..> DGE : traza
E ..> devent : traza
DVC---DGC
DGC----dcal
dcal---DGE
DGE----devent

@enduml